-- Create polls table
CREATE TABLE IF NOT EXISTS polls (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('poll', 'icebreaker')),
    question TEXT NOT NULL,
    option_1 TEXT,
    option_2 TEXT,
    option_3 TEXT,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'live', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create poll_responses table
CREATE TABLE IF NOT EXISTS poll_responses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    poll_id UUID NOT NULL REFERENCES polls(id) ON DELETE CASCADE,
    attendee_identifier TEXT NOT NULL,
    selected_option TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(poll_id, attendee_identifier)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_polls_event_id ON polls(event_id);
CREATE INDEX IF NOT EXISTS idx_polls_status ON polls(status);
CREATE INDEX IF NOT EXISTS idx_poll_responses_poll_id ON poll_responses(poll_id);

-- Add comments for documentation
COMMENT ON TABLE polls IS 'Stores smart polls and icebreakers generated by AI or created manually by event organizers';
COMMENT ON TABLE poll_responses IS 'Stores attendee responses to polls with unique constraint to prevent duplicate responses';
COMMENT ON COLUMN polls.type IS 'Either "poll" (with options) or "icebreaker" (open-ended)';
COMMENT ON COLUMN polls.status IS 'Poll lifecycle: draft -> live -> closed';
COMMENT ON COLUMN poll_responses.attendee_identifier IS 'Anonymous identifier for tracking responses (browser fingerprint or session ID)';
